spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@123
  #security:
   # user:
    #  name: rohit
     # password: rohit
     # roles: ADMIN

  #JPA Settings
  jpa.hibernate.ddl_auto: create
  jpa.show-sql: true

server:
  port: 8088

